#!/usr/bin/env bash
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WEB_ROOT="${WEB_ROOT:-$PROJECT_DIR/frontend/releases}"
"$PROJECT_DIR/scripts/build_web_domly.sh"
"$PROJECT_DIR/scripts/build_web_domly_pro.sh"
"$PROJECT_DIR/scripts/build_web_admin.sh"
release="$(date -u +%Y%m%dT%H%M%S)-$(git -C "$PROJECT_DIR" rev-parse --short HEAD)"
mkdir -p "$WEB_ROOT/$release/customer" "$WEB_ROOT/$release/pro" "$WEB_ROOT/$release/admin"
cp -a "$PROJECT_DIR/build/web-domly/." "$WEB_ROOT/$release/customer/"
cp -a "$PROJECT_DIR/build/web-pro/." "$WEB_ROOT/$release/pro/"
cp -a "$PROJECT_DIR/build/web-admin/." "$WEB_ROOT/$release/admin/"
chmod 755 "$WEB_ROOT"
chmod -R a+rX "$WEB_ROOT/$release"
ln -s "$release" "$WEB_ROOT/current.next"
mv -Tf "$WEB_ROOT/current.next" "$WEB_ROOT/current"
echo "Web release prepared for nginx: $WEB_ROOT/current"
